// src/common/enums/notification-type.enum.ts
export enum NotificationType {
  // Order notifications
  ORDER_CREATED = 'ORDER_CREATED',
  ORDER_CONFIRMED = 'ORDER_CONFIRMED',
  ORDER_CANCELLED = 'ORDER_CANCELLED',
  ORDER_SHIPPED = 'ORDER_SHIPPED',
  ORDER_DELIVERED = 'ORDER_DELIVERED',
  ORDER_REFUNDED = 'ORDER_REFUNDED',
  ORDER_ITEM_STATUS_UPDATED = 'ORDER_ITEM_STATUS_UPDATED',

  // Inventory notifications
  LOW_STOCK_ALERT = 'LOW_STOCK_ALERT',
  OUT_OF_STOCK = 'OUT_OF_STOCK',
  STOCK_REPLENISHED = 'STOCK_REPLENISHED',

  // Payment notifications
  PAYMENT_RECEIVED = 'PAYMENT_RECEIVED',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  REFUND_PROCESSED = 'REFUND_PROCESSED',

  // Review notifications
  NEW_REVIEW = 'NEW_REVIEW',
  REVIEW_RESPONSE_NEEDED = 'REVIEW_RESPONSE_NEEDED',

  // System notifications
  SYSTEM_ALERT = 'SYSTEM_ALERT',
  MAINTENANCE = 'MAINTENANCE',

  // Vendor notifications
  VENDOR_APPROVED = 'VENDOR_APPROVED',
  VENDOR_SUSPENDED = 'VENDOR_SUSPENDED',
  PAYOUT_PROCESSED = 'PAYOUT_PROCESSED',
}
