export const mockProducts = [
  {
    id: "1",
    name: "Premium Wireless Headphones",
    slug: "premium-wireless-headphones",
    price: 299.99,
    originalPrice: 399.99,
    image: "/premium-wireless-headphones.png",
    rating: 4.5,
    reviews: 128,
    category: "electronics",
    vendor: "TechMart",
    vendorSlug: "techmart",
    description: "Experience pristine audio with active noise cancellation and 30-hour battery life.",
    inStock: true,
  },
  {
    id: "2",
    name: "Organic Cotton T-Shirt",
    slug: "organic-cotton-tshirt",
    price: 49.99,
    originalPrice: 79.99,
    image: "/organic-cotton-tshirt.png",
    rating: 4.8,
    reviews: 256,
    category: "apparel",
    vendor: "Fashion Co",
    vendorSlug: "fashion-co",
    description: "Sustainable, comfortable, and stylish. Made from 100% organic cotton.",
    inStock: true,
  },
  {
    id: "3",
    name: "Stainless Steel Water Bottle",
    slug: "stainless-steel-water-bottle",
    price: 34.99,
    originalPrice: 49.99,
    image: "/stainless-steel-bottle.png",
    rating: 4.6,
    reviews: 512,
    category: "home",
    vendor: "EcoLiving",
    vendorSlug: "ecoliving",
    description: "Keep your drinks at the perfect temperature for up to 24 hours.",
    inStock: true,
  },
  {
    id: "4",
    name: "Professional Camera Tripod",
    slug: "professional-camera-tripod",
    price: 149.99,
    originalPrice: 199.99,
    image: "/professional-camera-tripod.jpg",
    rating: 4.7,
    reviews: 89,
    category: "electronics",
    vendor: "PhotoPro",
    vendorSlug: "photopro",
    description: "Lightweight yet sturdy tripod for all your photography needs.",
    inStock: true,
  },
  {
    id: "5",
    name: "Yoga Mat Premium",
    slug: "yoga-mat-premium",
    price: 59.99,
    originalPrice: 89.99,
    image: "/premium-yoga-mat.png",
    rating: 4.4,
    reviews: 201,
    category: "fitness",
    vendor: "FitLife",
    vendorSlug: "fitlife",
    description: "Non-slip, cushioned yoga mat perfect for all fitness levels.",
    inStock: true,
  },
  {
    id: "6",
    name: "Minimalist Desk Lamp",
    slug: "minimalist-desk-lamp",
    price: 79.99,
    originalPrice: 119.99,
    image: "/minimalist-desk-lamp.png",
    rating: 4.9,
    reviews: 145,
    category: "home",
    vendor: "DesignWorks",
    vendorSlug: "designworks",
    description: "Modern LED desk lamp with adjustable brightness and color temperature.",
    inStock: true,
  },
  {
    id: "7",
    name: "Bluetooth Speaker Compact",
    slug: "bluetooth-speaker-compact",
    price: 89.99,
    originalPrice: 129.99,
    image: "/bluetooth-speaker-compact.jpg",
    rating: 4.3,
    reviews: 378,
    category: "electronics",
    vendor: "SoundTech",
    vendorSlug: "soundtech",
    description: "Portable speaker with 12-hour battery and 360° sound.",
    inStock: false,
  },
  {
    id: "8",
    name: "Ceramic Plant Pot",
    slug: "ceramic-plant-pot",
    price: 29.99,
    originalPrice: 44.99,
    image: "/ceramic-plant-pot.png",
    rating: 4.6,
    reviews: 92,
    category: "home",
    vendor: "GreenSpace",
    vendorSlug: "greenspace",
    description: "Beautiful handcrafted ceramic pot for your indoor plants.",
    inStock: true,
  },
  {
    id: "9",
    name: "Running Shoes Pro",
    slug: "running-shoes-pro",
    price: 129.99,
    originalPrice: 179.99,
    image: "/running-shoes-pro.jpg",
    rating: 4.7,
    reviews: 634,
    category: "fitness",
    vendor: "SportGear",
    vendorSlug: "sportgear",
    description: "Lightweight running shoes with superior cushioning and support.",
    inStock: true,
  },
  {
    id: "10",
    name: "Smart Watch Essentials",
    slug: "smart-watch-essentials",
    price: 199.99,
    originalPrice: 299.99,
    image: "/smartwatch-lifestyle.png",
    rating: 4.5,
    reviews: 456,
    category: "electronics",
    vendor: "TechMart",
    vendorSlug: "techmart",
    description: "Track your fitness and stay connected with our smart watch.",
    inStock: true,
  },
  {
    id: "11",
    name: "Coffee Maker Deluxe",
    slug: "coffee-maker-deluxe",
    price: 149.99,
    originalPrice: 249.99,
    image: "/coffee-maker-deluxe.jpg",
    rating: 4.8,
    reviews: 289,
    category: "home",
    vendor: "KitchenPro",
    vendorSlug: "kitchenpro",
    description: "Brew perfect coffee every time with our programmable coffee maker.",
    inStock: true,
  },
  {
    id: "12",
    name: "Notebook Set",
    slug: "notebook-set",
    price: 24.99,
    originalPrice: 34.99,
    image: "/notebook-set.png",
    rating: 4.4,
    reviews: 167,
    category: "stationery",
    vendor: "PaperCo",
    vendorSlug: "paperco",
    description: "Premium quality notebooks perfect for journaling and notes.",
    inStock: true,
  },
]

export const mockCategories = [
  { id: "1", name: "Electronics", slug: "electronics", image: "/electronics-components.png" },
  { id: "2", name: "Apparel", slug: "apparel", image: "/apparel-clothing.jpg" },
  { id: "3", name: "Home & Garden", slug: "home", image: "/lush-home-garden.png" },
  { id: "4", name: "Fitness", slug: "fitness", image: "/diverse-fitness-equipment.png" },
  { id: "5", name: "Stationery", slug: "stationery", image: "/stationery-flatlay.png" },
  { id: "6", name: "Beauty", slug: "beauty", image: "/beauty-products-collection.png" },
]

export const mockVendors = [
  {
    id: "1",
    name: "TechMart",
    slug: "techmart",
    logo: "/techmart-logo.jpg",
    description: "Leading electronics and tech products.",
    rating: 4.7,
    followers: 15234,
  },
  {
    id: "2",
    name: "Fashion Co",
    slug: "fashion-co",
    logo: "/elegant-fashion-logo.png",
    description: "Premium sustainable fashion and apparel.",
    rating: 4.6,
    followers: 8921,
  },
  {
    id: "3",
    name: "EcoLiving",
    slug: "ecoliving",
    logo: "/ecoliving-logo.jpg",
    description: "Eco-friendly products for sustainable living.",
    rating: 4.8,
    followers: 12456,
  },
]

export const mockOrders = [
  {
    id: "ORD-001",
    date: "2026-01-15",
    total: 299.99,
    status: "delivered",
    items: 1,
  },
  {
    id: "ORD-002",
    date: "2026-01-10",
    total: 149.98,
    status: "processing",
    items: 2,
  },
  {
    id: "ORD-003",
    date: "2026-01-05",
    total: 89.99,
    status: "shipped",
    items: 1,
  },
]

export const mockWishlist = [mockProducts[0], mockProducts[2], mockProducts[5]]
