apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-service-sa
  namespace: multivendor-platform
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-gateway-sa
  namespace: multivendor-platform
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: multivendor-platform
  name: pod-reader
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: multivendor-platform
  name: read-pods
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-reader
subjects:
  - kind: ServiceAccount
    name: auth-service-sa
    namespace: multivendor-platform
  - kind: ServiceAccount
    name: api-gateway-sa
    namespace: multivendor-platform