// src/common/constants/error-codes.constant.ts
export const ERROR_CODES = {
  // Authentication
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  REFRESH_TOKEN_EXPIRED: 'REFRESH_TOKEN_EXPIRED',

  // Authorization
  FORBIDDEN: 'FORBIDDEN',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
  DOMAIN_RESTRICTED: 'DOMAIN_RESTRICTED',
  OPERATION_NOT_ALLOWED: 'OPERATION_NOT_ALLOWED',

  // Validation
  BAD_REQUEST: 'BAD_REQUEST',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_INPUT: 'INVALID_INPUT',

  // Query
  QUERY_TOO_COMPLEX: 'QUERY_TOO_COMPLEX',
  QUERY_TOO_DEEP: 'QUERY_TOO_DEEP',
  TOO_MANY_ALIASES: 'TOO_MANY_ALIASES',
  PERSISTED_QUERY_NOT_FOUND: 'PERSISTED_QUERY_NOT_FOUND',

  // Rate limiting
  RATE_LIMITED: 'RATE_LIMITED',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',

  // Service errors
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  GATEWAY_TIMEOUT: 'GATEWAY_TIMEOUT',
  BAD_GATEWAY: 'BAD_GATEWAY',
  SUBGRAPH_ERROR: 'SUBGRAPH_ERROR',

  // General
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
